# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
warnings_are_errors: false
cache:
  packages: true
script:
- Rscript -e "rmarkdown::render_site()"
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  local_dir: _site/
  committer-from-gh: true
  on:
    branch: master
deploy:
  provider: script
  skip_cleanup: true
  script: bash deploy2karli.sh
  on:
    branch: foo
notifications:
  email: false

